export const AUCTION_GET_OPENINGS_REQUEST = 'AUCTION_GET_OPENINGS_REQUEST';
export const AUCTION_GET_OPENINGS_SUCCESS = 'AUCTION_GET_OPENINGS_SUCCESS';
export const AUCTION_GET_OPENINGS_FAIL = 'AUCTION_GET_OPENINGS_FAIL';
export const AUCTION_GET_OPENINGS_RESET = 'AUCTION_GET_OPENINGS_FAIL';

export const AUCTION_GET_TOP_TRENDING_REQUEST =
  'AUCTION_GET_TOP_TRENDING_REQUEST';
export const AUCTION_GET_TOP_TRENDING_SUCCESS =
  'AUCTION_GET_TOP_TRENDING_SUCCESS';
export const AUCTION_GET_TOP_TRENDING_FAIL = 'AUCTION_GET_TOP_TRENDING_FAIL';

export const AUCTION_GET_BY_ID_REQUEST = 'AUCTION_GET_BY_ID_REQUEST';
export const AUCTION_GET_BY_ID_SUCCESS = 'AUCTION_GET_BY_ID_SUCCESS';
export const AUCTION_GET_BY_ID_FAIL = 'AUCTION_GET_BY_ID_FAIL';

export const AUCTION_GET_MY_AUCTIONS_REQUEST =
  'AUCTION_GET_MY_AUCTIONS_REQUEST';
export const AUCTION_GET_MY_AUCTIONS_SUCCESS =
  'AUCTION_GET_MY_AUCTIONS_SUCCESS';
export const AUCTION_GET_MY_AUCTIONS_FAIL = 'AUCTION_GET_MY_AUCTIONS_FAIL';

export const AUCTION_POST_REQUEST = 'AUCTION_POST_REQUEST';
export const AUCTION_POST_SUCCESS = 'AUCTION_POST_SUCCESS';
export const AUCTION_POST_FAIL = 'AUCTION_POST_FAIL';
export const AUCTION_POST_RESET = 'AUCTION_POST_RESET';

export const AUCTION_DELETE_REQUEST = 'AUCTION_DELETE_REQUEST';
export const AUCTION_DELETE_SUCCESS = 'AUCTION_DELETE_SUCCESS';
export const AUCTION_DELETE_FAIL = 'AUCTION_DELETE_FAIL';
export const AUCTION_DELETE_RESET = 'AUCTION_DELETE_RESET';

export const AUCTION_SUBMIT_REQUEST = 'AUCTION_SUBMIT_REQUEST';
export const AUCTION_SUBMIT_SUCCESS = 'AUCTION_SUBMIT_SUCCESS';
export const AUCTION_SUBMIT_FAIL = 'AUCTION_SUBMIT_FAIL';
export const AUCTION_SUBMIT_RESET = 'AUCTION_SUBMIT_RESET';
