export const AUCTION_GET_OPENINGS_REQUEST = 'AUCTION_GET_OPENINGS_REQUEST';
export const AUCTION_GET_OPENINGS_SUCCESS = 'AUCTION_GET_OPENINGS_SUCCESS';
export const AUCTION_GET_OPENINGS_FAIL = 'AUCTION_GET_OPENINGS_FAIL';

export const AUCTION_GET_TOP_TRENDING_REQUEST =
  'AUCTION_GET_TOP_TRENDING_REQUEST';
export const AUCTION_GET_TOP_TRENDING_SUCCESS =
  'AUCTION_GET_TOP_TRENDING_SUCCESS';
export const AUCTION_GET_TOP_TRENDING_FAIL = 'AUCTION_GET_TOP_TRENDING_FAIL';
