export const BID_GET_BY_AUCTION_ID_REQUEST = 'BID_GET_BY_AUCTION_ID_REQUEST';
export const BID_GET_BY_AUCTION_ID_SUCCESS = 'BID_GET_BY_AUCTION_ID_SUCCESS';
export const BID_GET_BY_AUCTION_ID_FAIL = 'BID_GET_BY_AUCTION_ID_FAIL';

export const BID_POST_BY_AUCTION_ID_REQUEST = 'BID_POST_BY_AUCTION_ID_REQUEST';
export const BID_POST_BY_AUCTION_ID_SUCCESS = 'BID_POST_BY_AUCTION_ID_SUCCESS';
export const BID_POST_BY_AUCTION_ID_FAIL = 'BID_POST_BY_AUCTION_ID_FAIL';
export const BID_POST_BY_AUCTION_ID_RESET = 'BID_POST_BY_AUCTION_ID_RESET';
