export const ITEM_PUT_REQUEST = 'ITEM_PUT_REQUEST';
export const ITEM_PUT_SUCCESS = 'ITEM_PUT_SUCCESS';
export const ITEM_PUT_FAIL = 'ITEM_PUT_FAIL';
export const ITEM_PUT_RESET = 'ITEM_PUT_RESET';

export const ITEM_UPLOAD_IMAGE_REQUEST = 'ITEM_UPLOAD_IMAGE_REQUEST';
export const ITEM_UPLOAD_IMAGE_SUCCESS = 'ITEM_UPLOAD_IMAGE_SUCCESS';
export const ITEM_UPLOAD_IMAGE_FAIL = 'ITEM_UPLOAD_IMAGE_FAIL';
export const ITEM_UPLOAD_IMAGE_RESET = 'ITEM_UPLOAD_IMAGE_RESET';
