export const NOTIFICATION_GET_MY_NOTIFICATIONS_REQUEST =
  'NOTIFICATION_GET_MY_NOTIFICATIONS_REQUEST';
export const NOTIFICATION_GET_MY_NOTIFICATIONS_SUCCESS =
  'NOTIFICATION_GET_MY_NOTIFICATIONS_SUCCESS';
export const NOTIFICATION_GET_MY_NOTIFICATIONS_FAIL =
  'NOTIFICATION_GET_MY_NOTIFICATIONS_FAIL';
export const NOTIFICATION_GET_MY_NOTIFICATIONS_SEEN =
  'NOTIFICATION_GET_MY_NOTIFICATIONS_SEEN';
export const NOTIFICATION_GET_MY_NOTIFICATIONS_RESET =
  'NOTIFICATION_GET_MY_NOTIFICATIONS_RESET';
