export const PROFILE_GET_BY_ID_REQUEST = 'PROFILE_GET_BY_ID_REQUEST';
export const PROFILE_GET_BY_ID_SUCCESS = 'PROFILE_GET_BY_ID_SUCCESS';
export const PROFILE_GET_BY_ID_FAIL = 'PROFILE_GET_BY_ID_FAIL';

export const PROFILE_CHANGE_PASSWORD_REQUEST =
  'PROFILE_CHANGE_PASSWORD_REQUEST';
export const PROFILE_CHANGE_PASSWORD_SUCCESS =
  'PROFILE_CHANGE_PASSWORD_SUCCESS';
export const PROFILE_CHANGE_PASSWORD_FAIL = 'PROFILE_CHANGE_PASSWORD_FAIL';
export const PROFILE_CHANGE_PASSWORD_RESET = 'PROFILE_CHANGE_PASSWORD_RESET';
