export const REPORT_POST_REQUEST = 'REPORT_POST_REQUEST';
export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS';
export const REPORT_POST_FAIL = 'REPORT_POST_FAIL';
export const REPORT_POST_RESET = 'REPORT_POST_RESET';

//admin

export const REPORT_ADMIN_GET_ALL_REQUEST = 'REPORT_ADMIN_GET_ALL_REQUEST';
export const REPORT_ADMIN_GET_ALL_SUCCESS = 'REPORT_ADMIN_GET_ALL_SUCCESS';
export const REPORT_ADMIN_GET_ALL_FAIL = 'REPORT_ADMIN_GET_ALL_FAIL';

export const REPORT_ADMIN_JUDGE_REQUEST = 'REPORT_ADMIN_JUDGE_REQUEST';
export const REPORT_ADMIN_JUDGE_SUCCESS = 'REPORT_ADMIN_JUDGE_SUCCESS';
export const REPORT_ADMIN_JUDGE_FAIL = 'REPORT_ADMIN_JUDGE_FAIL';
export const REPORT_ADMIN_JUDGE_RESET = 'REPORT_ADMIN_JUDGE_RESET';

export const REPORT_ADMIN_DELETE_REQUEST = 'REPORT_ADMIN_DELETE_REQUEST';
export const REPORT_ADMIN_DELETE_SUCCESS = 'REPORT_ADMIN_DELETE_SUCCESS';
export const REPORT_ADMIN_DELETE_FAIL = 'REPORT_ADMIN_DELETE_FAIL';
export const REPORT_ADMIN_DELETE_RESET = 'REPORT_ADMIN_DELETE_RESET';
